const dotenv = require('dotenv');

dotenv.config();

const jobPostSites = [
  "indeed",
  "linkedin",
  "monster",
  "glassdoor",
  "careerbuilder",
  "ziprecruiter",
  "simplyhired",
  "dice",
  "idealist",
  "usajobs",
  "snagajob",
  "craigslist",
  "upwork",
  "freelancer",
  "elance",
  "fiverr",
  "naukri",
  "shine",
  "timesjobs",
  "freshersworld",
  "angel.co",
  "linkedin",
  "dribbble",
  "github jobs",
  "stack overflow jobs",
  "remote OK",
  "we work remotely",
  "remote.co",
  "justremote",
  "virtual vocations",
  "flexjobs",
  "indeed remote",
  "google for jobs",
  "careerjet",
  "juju",
  "linkup",
  "neuvoo",
  "jobisjob",
  "jobrapido",
  "careerjet",
  "jobs2careers",
  "gumtree",
  "reed",
  "totaljobs",
  "workopolis",
  "jobbank",
  "jobboom",
  "jooble",
  "jobindex",
  "jobcase",
  "glassdoor",
  "ladders",
  "monster",
  "ziprecruiter",
  "simplyhired",
  "dice",
  "idealist",
  "usajobs",
  "snagajob",
  "craigslist",
  "upwork",
  "freelancer",
  "elance",
  "fiverr",
  "naukri",
  "shine",
  "timesjobs",
  "freshersworld",
  "angel.co",
  "linkedin",
  "dribbble",
  "github jobs",
  "stack overflow jobs",
  "remote OK",
  "we work remotely",
  "remote.co",
  "justremote",
  "virtual vocations",
  "flexjobs",
  "indeed remote",
  "google for jobs",
  "careerjet",
  "juju",
  "linkup",
  "neuvoo",
  "jobisjob",
  "jobrapido",
  "careerjet",
  "jobs2careers",
  "gumtree",
  "reed",
  "totaljobs",
  "workopolis",
  "jobbank",
  "jobboom",
  "jooble",
  "jobindex",
  "jobcase",
  "idealista",
  "creativepool",
  "coroflot",
  "krop",
  "behance",
  "golang jobs",
  "python.org/jobs",
  "ruby now",
  "weworkmeteor",
  "hasjob",
  "careers.javascriptweekly",
  "angularjobs",
  "larajobs",
  "jobs.vuejs",
  "gamedevjobs.io",
  "unity3d",
  "jobs.gamasutra",
  "gamejobs.co",
  "jobs.gameindustry.biz",
  "gisjobs",
  "gisuser",
  "geojobs.biz",
  "esri",
  "environmental jobs",
  "conservation job board",
  "ecojobs",
  "greenjobs",
  "sustainable business",
  "hcareers",
  "ihirehospitality",
  "culinaryagents",
  "bartend.com",
  "workinretail",
  "theladders",
  "jobdiagnosis",
  "jora",
  "mitula",
  "us.jobs",
  "us.jobrapido",
  "jobsgalore",
  "jobvertise",
  "jobhat",
  "jobisite",
  "postjobfree",
  "veteran jobs",
  "militaryhire",
  "hirepurpose",
  "vetjobs",
  "clearancejobs",
  "hireveterans",
  "recruitmilitary",
  "taonline",
  "military.com/jobsearch",
  "transitioning military",
  "jobsonline",
  "bestjobsusa",
  "veteranjoblistings",
  "veteranjobs.net",
  "veteransjobexchange",
  "justveteransjobs",
  "vettedhonor",
  "hiringourheroes",
  "militaryfriendly",
  "gi jobs",
  "hcareers",
  "ihirehospitality",
  "culinaryagents",
  "bartend.com",
  "workinretail",
  "theladders",
  "jobdiagnosis",
  "jora",
  "mitula",
  "careers",
  "jobs"
];


const isProd = process.env.APP_ENV === 'PROD';

const cookieOptions = {
  httpOnly: true,
  secure: isProd,             // must be true in production for HTTPS
  sameSite: isProd ? 'none' : 'lax', // 'none' required for cross-origin in production
  maxAge: 7 * 24 * 60 * 60 * 1000, // 7 days default
  path: '/',
  // Don't set domain in production to allow cross-domain cookies
  domain: isProd ? undefined : 'localhost'
};

const tokenkeyName = `${process.env.APP_ENV}:hushwork-root`;
const guestKey = `${tokenkeyName}:guest_id`;

// Better Auth session cookie name (separate from JWT to avoid conflicts)
const betterAuthSessionCookie = `${process.env.APP_ENV}:hushwork-session`;

// All authentication-related cookie names
const authCookieNames = {
  token: tokenkeyName,
  refreshToken: `${tokenkeyName}:refresh`,
  betterAuthSession: betterAuthSessionCookie,
  isAuthenticated: 'isAuthenticated',
  guest: guestKey
};


const projection = {
  user_job_role: 1,
  is_anonymous: 1,
  is_email_verified: 1,
  user_bio: 1,
  user_current_company_name: 1,
  user_id: 1,
  user_job_experience: 1,
  user_location: 1,
  public_user_name: 1,
  followings: 1,
  followers: 1,
  avatar: 1,
  user_public_profile_pic: 1,
  pending_followings: 1,
  profile_details: 1,
  _id: 1,
  profession: 1,
  academic_level: 1,
  field_of_study: 1,
  hobbies: 1,
  last_active_at: 1,
  is_admin: 1,
  access: 1
};

module.exports = {
  jobPostSites,
  tokenkeyName,
  cookieOptions,
  isProd,
  guestKey,
  projection,
  betterAuthSessionCookie,
  authCookieNames
}
