const { isProd } = require("..");

const jobPostSites = [
    "indeed",
    "linkedin",
    "monster",
    "glassdoor",
    "careerbuilder",
    "ziprecruiter",
    "simplyhired",
    "dice",
    "idealist",
    "usajobs",
    "snagajob",
    "craigslist",
    "upwork",
    "freelancer",
    "elance",
    "fiverr",
    "naukri",
    "shine",
    "timesjobs",
    "freshersworld",
    "angel.co",
    "linkedin",
    "dribbble",
    "github jobs",
    "stack overflow jobs",
    "remote OK",
    "we work remotely",
    "remote.co",
    "justremote",
    "virtual vocations",
    "flexjobs",
    "indeed remote",
    "google for jobs",
    "careerjet",
    "juju",
    "linkup",
    "neuvoo",
    "jobisjob",
    "jobrapido",
    "careerjet",
    "jobs2careers",
    "gumtree",
    "reed",
    "totaljobs",
    "workopolis",
    "jobbank",
    "jobboom",
    "jooble",
    "jobindex",
    "jobcase",
    "glassdoor",
    "ladders",
    "monster",
    "ziprecruiter",
    "simplyhired",
    "dice",
    "idealist",
    "usajobs",
    "snagajob",
    "craigslist",
    "upwork",
    "freelancer",
    "elance",
    "fiverr",
    "naukri",
    "shine",
    "timesjobs",
    "freshersworld",
    "angel.co",
    "linkedin",
    "dribbble",
    "github jobs",
    "stack overflow jobs",
    "remote OK",
    "we work remotely",
    "remote.co",
    "justremote",
    "virtual vocations",
    "flexjobs",
    "indeed remote",
    "google for jobs",
    "careerjet",
    "juju",
    "linkup",
    "neuvoo",
    "jobisjob",
    "jobrapido",
    "careerjet",
    "jobs2careers",
    "gumtree",
    "reed",
    "totaljobs",
    "workopolis",
    "jobbank",
    "jobboom",
    "jooble",
    "jobindex",
    "jobcase",
    "idealista",
    "creativepool",
    "coroflot",
    "krop",
    "behance",
    "golang jobs",
    "python.org/jobs",
    "ruby now",
    "weworkmeteor",
    "hasjob",
    "careers.javascriptweekly",
    "angularjobs",
    "larajobs",
    "jobs.vuejs",
    "gamedevjobs.io",
    "unity3d",
    "jobs.gamasutra",
    "gamejobs.co",
    "jobs.gameindustry.biz",
    "gisjobs",
    "gisuser",
    "geojobs.biz",
    "esri",
    "environmental jobs",
    "conservation job board",
    "ecojobs",
    "greenjobs",
    "sustainable business",
    "hcareers",
    "ihirehospitality",
    "culinaryagents",
    "bartend.com",
    "workinretail",
    "theladders",
    "jobdiagnosis",
    "jora",
    "mitula",
    "us.jobs",
    "us.jobrapido",
    "jobsgalore",
    "jobvertise",
    "jobhat",
    "jobisite",
    "postjobfree",
    "veteran jobs",
    "militaryhire",
    "hirepurpose",
    "vetjobs",
    "clearancejobs",
    "hireveterans",
    "recruitmilitary",
    "taonline",
    "military.com/jobsearch",
    "transitioning military",
    "jobsonline",
    "bestjobsusa",
    "veteranjoblistings",
    "veteranjobs.net",
    "veteransjobexchange",
    "justveteransjobs",
    "vettedhonor",
    "hiringourheroes",
    "militaryfriendly",
    "gi jobs",
    "hcareers",
    "ihirehospitality",
    "culinaryagents",
    "bartend.com",
    "workinretail",
    "theladders",
    "jobdiagnosis",
    "jora",
    "mitula",
    "careers",
    "jobs"
];


const tokenkeyName = "hush-work-key"


const cookieOptions = {
    httpOnly: true,
    secure: isProd,             // must be true in production
    sameSite: isProd ? 'none' : 'lax', // cross-origin needs None in prod
    maxAge: 7 * 24 * 60 * 60 * 1000,
    path: '/',
    domain: isProd ? undefined : 'localhost'
};


module.exports = { jobPostSites, tokenkeyName, cookieOptions }
