'use strict';

/**
 * Static blocklist of known disposable / temp email providers.
 * Source: curated from the open-source disposable-email-domains project.
 * Add new domains here as they appear. Keep sorted alphabetically.
 */
const DISPOSABLE_DOMAINS = new Set([
  '0-mail.com', '0815.ru', '0clickemail.com', '0wnd.net', '0wnd.org',
  '10mail.com', '10minutemail.cf', '10minutemail.com', '10minutemail.de',
  '10minutemail.ga', '10minutemail.gg', '10minutemail.gq', '10minutemail.info',
  '10minutemail.io', '10minutemail.ml', '10minutemail.net', '10minutemail.nl',
  '10minutemail.org', '10minutemail.pl', '10minutemail.pro', '10minutemail.ru',
  '10minutemail.us', '10minutemailbox.com', '20minutemail.com', '20minutemail.it',
  '21cn.com', '33mail.com', '3d-painting.com', '4warding.com',
  'agedmail.com', 'agger.ro', 'agustusdev.com', 'ahem.email',
  'airsi.de', 'ajaxapp.net', 'akapost.com', 'aliasbox.com',
  'aliasinbox.com', 'aliceadsl.fr', 'alltimenews.pk', 'aloaha.com',
  'altmails.com', 'amail.club', 'amail1.com', 'amailbox.net',
  'anonymail.dk', 'anonymousmail.org', 'antichef.com', 'antichef.net',
  'antispam.de', 'antispammail.de', 'armyspy.com', 'arybt.com',
  'asdas.de', 'asdasd.nl', 'asdfgh.dk', 'astroempires.com',
  'at0.net', 'avpa.nl', 'azmeil.tk',
  'b2cmail.de', 'badpotato.tk', 'banit.club', 'banit.me',
  'barryogorman.com', 'baxomale.ht.cx', 'bccto.me', 'bcaoo.com',
  'beefmilk.com', 'binka.me', 'blackmarket.to', 'blitzermedia.com',
  'bloq.ro', 'bmpk.org', 'bobmail.info', 'bodhi.lawlita.com',
  'bofthew.com', 'bootybay.de', 'boun.cr', 'bouncr.com',
  'boxformail.in', 'brefmail.com', 'broadbandninja.com', 'bspamfree.org',
  'buffemail.com', 'bugmenot.com', 'bumpymail.com', 'bund.us',
  'burnthespam.info', 'buymoreplays.com', 'bxox.info', 'byom.de',
  'c0rtana.cf', 'c0rtana.ga', 'cachedot.net', 'card.zp.ua',
  'casualdx.com', 'cbair.com', 'cek.pm', 'cellurl.com',
  'centermail.com', 'centermail.net', 'cfo2go.ro', 'chammy.info',
  'cheatmail.de', 'chielo.com', 'chogmail.com', 'chong-mail.net',
  'choicemail1.com', 'christopherfretz.com', 'ciga.ro', 'civx.org',
  'ckiso.com', 'clandest.in', 'clrmail.com', 'cmail.club',
  'cmail.com', 'cmail.net', 'cmail.org', 'cntv.cn',
  'cool.fr.nf', 'coole-files.de', 'correo.blogos.net', 'cosmorph.com',
  'courriel.fr.nf', 'courrieltemporaire.com', 'crapmail.org', 'crazymailing.com',
  'crossroadsmail.com', 'cursosbr.com', 'curryworld.de',
  'd3p.dk', 'dacoolest.com', 'daemsteam.com', 'dayrep.com',
  'deadaddress.com', 'deadletter.ga', 'deagot.com', 'dealja.com',
  'deipartam.com', 'despam.it', 'despammed.com', 'devnullmail.com',
  'dharmatel.net', 'digitalsanctuary.com', 'dingbone.com', 'discard.email',
  'discardmail.com', 'discardmail.de', 'discos.venturas.com',
  'dispostable.com', 'dm.w3internet.co.uk', 'dodgeit.com', 'dodgit.com',
  'dontsendmespam.de', 'dot-ml.ml', 'doten.ml', 'drbob.net',
  'drdrb.com', 'drdrb.net', 'dsiay.com', 'dspam.com',
  'dump-email.info', 'dumpandfuck.com', 'dumpmail.de',
  'dumpyemail.com', 'durandinterstellar.com',
  'e4ward.com', 'edgex.ru', 'email60.com', 'emaildienst.de',
  'emailias.com', 'emailigo.com', 'emailinfive.com', 'emailmiser.com',
  'emailproxsy.com', 'emailsensei.com', 'emailtemporanea.com',
  'emailtemporanea.net', 'emailtemporar.ro', 'emailtemporario.com.br',
  'emailthe.net', 'emailtmp.com', 'emailwarden.com', 'emailx.at.hm',
  'emailxfer.com', 'emz.net', 'enterto.com', 'ephemail.net',
  'ero-tube.org', 'etranquil.com', 'etranquil.net', 'etranquil.org',
  'evopo.com', 'example.com', 'explodemail.com', 'extremail.ru',
  'ez.lv',
  'f4k.es', 'facebook.de', 'fackme.gq', 'fadingemail.com',
  'fakedemail.com', 'fakeinbox.cf', 'fakeinbox.com', 'fakeinbox.ga',
  'fakeinbox.info', 'fakeinbox.ml', 'fakeinbox.tk', 'fakemailz.com',
  'fammix.com', 'fansworldwide.de', 'fastacura.com', 'fastchevy.com',
  'fastchrysler.com', 'fastdodge.com', 'fastford.com', 'fastgm.com',
  'fastgmc.com', 'fastjetta.com', 'fastmail.com', 'fastmazda.com',
  'fastnissan.com', 'fastsuzuki.com', 'fasttoyota.com', 'fastyamaha.com',
  'fatflap.com', 'fbi.hu', 'fdcserver.net', 'fddns.ml',
  'fightallspam.com', 'fiifke.de', 'filbert.com', 'filzmail.com',
  'fivemail.de', 'fixmail.tk', 'fizmail.com', 'fleckens.hu',
  'fo.lk', 'forcematch.com', 'forspam.net', 'forward.cat',
  'frapmail.com', 'freeinbox.cyou', 'freemail.ms', 'friendlymail.co.uk',
  'front14.org', 'fsociety.cf', 'fun2.biz', 'fun64.com',
  'funnymail.de', 'furzauflunge.de', 'fuw.ch', 'fxprix.com',
  'garbagemail.org', 'gedmail.win', 'gehensiemirnichtaufdennerv.de',
  'genderfuck.net', 'get-mail.cf', 'get-mail.ga', 'get-mail.ml',
  'get-mail.tk', 'get1mail.com', 'getairmail.com', 'geteit.com',
  'getmails.eu', 'getonemail.com', 'getonemail.net', 'getnada.com',
  'gett.icu', 'gez.com', 'ghosttexter.de', 'girlmail.win',
  'gishpuppy.com', 'giveh2o.info', 'glitch.sx', 'globxmail.com',
  'goemailgo.com', 'gomail.in', 'gorillaswithdirtyarmpits.com',
  'gottahaveit.com', 'gowikibooks.com', 'gowikicampus.com',
  'gowikicars.com', 'gowikifilms.com', 'gowikigames.com',
  'gowikimusic.com', 'gowikinetwork.com', 'gowikitravel.com',
  'gowikitv.com', 'grandmamail.com', 'grandmasmail.com', 'grr.la',
  'gsrv.co.uk', 'guerillamail.biz', 'guerillamail.com', 'guerillamail.de',
  'guerillamail.info', 'guerillamail.net', 'guerillamail.org',
  'guerillamail.us', 'guerrillamail.biz', 'guerrillamail.com',
  'guerrillamail.de', 'guerrillamail.info', 'guerrillamail.net',
  'guerrillamail.org', 'guerrillamailblock.com', 'gustr.com',
  'h.mintemail.com', 'habitbull.com', 'haltospam.com',
  'harakirimail.com', 'hat-geld.de', 'hatespam.org', 'heldmail.com',
  'herp.in', 'hidemail.de', 'hidzz.com', 'hmamail.com',
  'hmh.ro', 'hopemail.biz', 'hotmai.com', 'hotmial.com',
  'hotpop.com', 'hulapla.de', 'hvastudiesucces.nl',
  'ieatspam.eu', 'ieatspam.info', 'igetspam.com', 'ihateyoualot.info',
  'iheartspam.org', 'imails.info', 'inboxalias.com', 'incognitomail.com',
  'incognitomail.net', 'incognitomail.org', 'inoutmail.de',
  'inoutmail.eu', 'inoutmail.info', 'inoutmail.net', 'insorg.org',
  'instantemailaddress.com', 'instantmail.fr', 'internet-e-mail.de',
  'internet-mail.de', 'ip6.li', 'irc.so', 'irish2me.com',
  'iwi.net',
  'jetable.com', 'jetable.fr.nf', 'jetable.net', 'jetable.org',
  'jnxjn.com', 'joelpet.com', 'joetestalot.com', 'junk.to',
  'junk1e.com', 'junkmail.com', 'junkmail.ga', 'junkmail.gq',
  'jupimail.com',
  'kasmail.com', 'kaspop.com', 'keepmymail.com', 'killmail.com',
  'killmail.net', 'kir.ch.tc', 'klassmaster.com', 'klassmaster.net',
  'kludgemush.com', 'knol-power.nl', 'kook.ml', 'koszmail.pl',
  'kurzepost.de', 'kwickgame.com',
  'l33r.eu', 'laoeq.com', 'lastmail.co', 'lavabit.com',
  'law.ms', 'lazyinbox.com', 'letthemeatspam.com', 'lhsdv.com',
  'lifebyfood.com', 'link2mail.net', 'litedrop.com', 'lol.ovpn.to',
  'lolfreak.net', 'lookugly.com', 'lortemail.dk', 'losemymail.com',
  'lovemeleaveme.com', 'lr78.com', 'lroid.com', 'lukop.dk',
  'm21.cc', 'mail-filter.com', 'mail-owl.com', 'mail-temporaire.fr',
  'mail.mezimages.net', 'mail1a.de', 'mail21.cc', 'mail2rss.org',
  'mail333.com', 'mail4trash.com', 'mailbucket.org', 'mailcat.biz',
  'mailcatch.com', 'maildrop.cc', 'maildrop.cf', 'maildrop.ga',
  'maildrop.gq', 'maildrop.ml', 'maileater.com', 'mailexpire.com',
  'mailfreeonline.com', 'mailguard.me', 'mailimate.com', 'mailin8r.com',
  'mailinater.com', 'mailinator.com', 'mailinator.net', 'mailinator.org',
  'mailinator.us', 'mailinator2.com', 'mailincubator.com', 'mailismagic.com',
  'mailitv.net', 'mailjunk.cf', 'mailjunk.ga', 'mailjunk.gq',
  'mailjunk.ml', 'mailjunk.tk', 'mailkutu.com', 'mailme.gq',
  'mailme.ir', 'mailme.lol', 'mailme24.com', 'mailmoth.com',
  'mailnew.com', 'mailnull.com', 'mailpick.biz', 'mailproxsy.com',
  'mailquack.com', 'mailrock.biz', 'mailsac.com', 'mailscrap.com',
  'mailshell.com', 'mailsiphon.com', 'mailslite.com', 'mailsoul.com',
  'mailtome.de', 'mailtothis.com', 'mailzilla.com', 'mailzilla.org',
  'makemetheking.com', 'malahov.de', 'manifestgenerator.com',
  'mbx.cc', 'mcdonald.cf', 'mcdonald.ga', 'mciek.com',
  'mega.zik.dj', 'meinspamschutz.de', 'meltmail.com', 'messagebeamer.de',
  'mezimages.net', 'mierdamail.com', 'mintemail.com', 'misterpinball.de',
  'mjukglass.nu', 'ml8.ca', 'mm.my', 'mmmmail.com',
  'mobileninja.co.uk', 'mohmal.com', 'mohmal.im', 'mohmal.in',
  'mohmal.tech', 'mohmal.top', 'moiasmail.com', 'monmail.fr.nf',
  'mooo.com', 'mox.pp.ua', 'mp3zig.com', 'mt2009.com',
  'mt2014.com', 'mugglenet.com', 'muhp.org', 'mundomail.net',
  'my10minutemail.com', 'myalias.pw', 'mymail.ro', 'myrealbox.com',
  'myspaceinc.com', 'myspaceinc.net', 'myspaceinc.org',
  'myspacepimpedup.com', 'mysugartime.com', 'mytempemail.com',
  'mytrashmail.com',
  'n1nja.org', 'naexs.com', 'naver.com', 'nbzmr.com',
  'nda.ag', 'neomailbox.com', 'nepwk.com', 'nervmich.net',
  'nervtmich.net', 'netvigilance.com', 'newfilm.ro', 'nextstopvalhalla.com',
  'nicholasimadp.com', 'nls.net', 'nnot.net', 'no-spam.ws',
  'nobulk.com', 'noclickemail.com', 'nomail.pw', 'nomail.xl.cx',
  'nomail2me.com', 'nomorespamemails.com', 'nonspam.eu', 'nospam.ze.tc',
  'nospam4.us', 'nospamfor.us', 'nospamthanks.info', 'notmailinator.com',
  'notrnailinator.com', 'now.im', 'nowhere.org', 'nwldx.com',
  'nwytg.net',
  'objectmail.com', 'obobbo.com', 'odnorazovoe.ru', 'ohaaa.de',
  'okrent.us', 'oneoffemail.com', 'oopi.org', 'open-mail.net',
  'opentrash.com', 'opoemail.com', 'ordinaryamerican.net', 'otherinbox.com',
  'ourklips.com', 'ourpreviewdomain.com', 'outlawspam.com',
  'ovpn.to', 'owlpic.com',
  'pancakemail.com', 'paplease.com', 'papierkorb.me', 'pcusers.otherinbox.com',
  'pepbot.com', 'pf.ximails.com', 'pfui.ru', 'phentermine-mortgages.com',
  'pickupmail.com', 'pillpeso.com', 'pimpedupmyspace.com', 'plasticpie.com',
  'plexolan.de', 'poczta.onet.pl', 'politikerclub.de', 'poopiemail.com',
  'popesodomy.com', 'postacı.ml', 'postacitesi.ml', 'postafree.com',
  'postino.ch', 'postonline.me', 'postpro.net', 'privacy.net',
  'privatdemail.net', 'proxymail.eu', 'prtnx.com', 'prtz.eu',
  'pubmail.io', 'punkass.com', 'putthisinyourspamdatabase.com',
  'qq.com', 'queuetimesstats.com', 'quickinbox.com', 'quickmail.nl',
  'quickmail.rock', 'quicksend.ch', 'qwickmail.com',
  'r4nd0m.de', 'rabiot.reisen', 'rainmail.win', 'randomail.net',
  'rcpt.at', 'recode.me', 'recursor.net', 'regbypass.comsafe-mail.net',
  'rejep.com', 'rklips.com', 'rkomo.com', 'rktfuk.ml',
  'rklips.com', 'rmqkr.net', 'rootfest.net', 'rppkn.com',
  'rtrtr.com', 'rudivid.com', 'ruffrey.com', 'rumgel.com',
  'runnerslife.de', 'rxan.net',
  's0ny.net', 'safe-mail.net', 'safetypost.de', 'sahem.ga',
  'sandelf.de', 'sanibase.com', 'sanstr.com', 'saynotospams.com',
  'schafmail.de', 'schredder.me', 'sdnr.it', 'sea-ex.com',
  'selfdestructingmail.com', 'selfdestructingmail.org', 'sendspamhere.com',
  'senseless-entertainment.com', 'services391.com', 'sfamo.com',
  'sharedmailbox.org', 'sharklasers.com', 'shieldedmail.com',
  'shiftmail.com', 'shishi-mail.com', 'shitmail.de', 'shitmail.org',
  'shitware.nl', 'shortmail.net', 'showslow.de', 'sify.com',
  'silentmail.info', 'sim-mail.com', 'siteposter.net', 'skeefmail.com',
  'skrx.tk', 'slippery.email', 'slopsbox.com', 'slow-mail.com',
  'smail.com', 'smashmail.de', 'smellfear.com', 'smtp99.com',
  'snakemail.com', 'sneakemail.com', 'sneakmail.de', 'snkmail.com',
  'sofimail.com', 'sogetthis.com', 'sofort-mail.de', 'sol.dk',
  'soodmail.com', 'soodo.com', 'spam.la', 'spam.su',
  'spam4.me', 'spamail.de', 'spamavert.com', 'spambob.com',
  'spambob.net', 'spambob.org', 'spambog.com', 'spambog.de',
  'spambog.ru', 'spambox.info', 'spambox.irishspringrealty.com',
  'spambox.us', 'spamcannon.com', 'spamcannon.net', 'spamcero.com',
  'spamcon.org', 'spamcorptastic.com', 'spamcowboy.com', 'spamcowboy.net',
  'spamcowboy.org', 'spamday.com', 'spamex.com', 'spamfree.eu',
  'spamfree24.de', 'spamfree24.eu', 'spamfree24.info', 'spamfree24.net',
  'spamfree24.org', 'spamgoes.in', 'spamgourmet.com', 'spamgourmet.net',
  'spamgourmet.org', 'spamherelots.com', 'spamhereplease.com',
  'spamhole.com', 'spamify.com', 'spaminator.de', 'spaminmotion.com',
  'spamkill.info', 'spaml.com', 'spaml.de', 'spammotel.com',
  'spammy.host', 'spamok.com', 'spamorama.com', 'spampa.com',
  'spampost.de', 'spamspot.com', 'spamstack.net', 'spamthis.co.uk',
  'spamthisplease.com', 'spamtrail.com', 'spamtrap.ro',
  'spamwc.de', 'spiceme.de', 'spikes.pw', 'spils.com',
  'spt.de', 'spybox.de', 'squizzy.de', 'ssoia.com',
  'startkeys.com', 'stinkefinger.net', 'stopspam.org', 'stuffmail.de',
  'stumpfwerk.com', 'subwithus.com', 'suremail.info', 'svk.jp',
  't-online.de.vu', 'tefl.ro', 'tele2.nl', 'temp-mail.com',
  'temp-mail.de', 'temp-mail.io', 'temp-mail.org', 'temp-mail.ru',
  'temp.emeraldwebmail.com', 'temp.headstrong.de', 'tempail.com',
  'tempalias.com', 'tempe-mail.com', 'tempemail.biz', 'tempemail.com',
  'tempemail.co.za', 'tempemail.net', 'tempemail.org', 'tempinbox.co.uk',
  'tempinbox.com', 'tempmail.de', 'tempmail.eu', 'tempmail.io',
  'tempmail.it', 'tempmail.net', 'tempmail.org', 'tempmail.us',
  'tempmail2.com', 'tempr.email', 'tempymail.com', 'tenminutemail.com',
  'thanksnospam.info', 'thc.st', 'theecologist.com', 'thisisnotmyrealemail.com',
  'throam.com', 'thrott.com', 'throwam.com', 'throwaway.email',
  'throwaways.net', 'throwmail.net', 'throwspam.net', 'tidni.com',
  'tilien.com', 'tm.mit.edu', 'tmpjr.me', 'tradermail.info',
  'tralalamail.com', 'trash-amil.com', 'trash-mail.at', 'trash-mail.com',
  'trash-mail.de', 'trash-mail.ga', 'trash-mail.gq', 'trash-mail.io',
  'trash-mail.ml', 'trash-mail.tk', 'trash.net', 'trash2009.com',
  'trash2010.com', 'trash2011.com', 'trashdevil.com', 'trashemail.de',
  'trashemails.de', 'trashimail.com', 'trashmail.at', 'trashmail.com',
  'trashmail.de', 'trashmail.io', 'trashmail.me', 'trashmail.net',
  'trashmail.org', 'trashmail.xyz', 'trashmailer.com', 'trashmail.top',
  'trashmailcontainer.com', 'trbvm.com', 'trickmail.net', 'trillianpro.com',
  'tryalert.com', 'ttirv.net', 'turual.com', 'twinmail.de',
  'twoweeks.ch', 'tyldd.com',
  'uggsrock.com', 'umail.net', 'uncle-bob.net', 'unimark.org',
  'unlimit.com', 'unmail.ru', 'unmail.xyz', 'uomail.xyz',
  'upliftnow.com', 'urgentmail.biz',
  'venompen.com', 'viewcastmedia.com', 'viewcastmedia.net',
  'viewcastmedia.org', 'vkcode.ru',
  'w3internet.co.uk', 'walala.org', 'walkmail.net', 'walkmail.ru',
  'webemail.me', 'webm4il.info', 'webtrash.de', 'wegwerfadresse.de',
  'wegwerf-email.at', 'wegwerf-email.de', 'wegwerf-email.net',
  'wegwerf-email.org', 'wegwerfadresse.net', 'wegwerfadresse.org',
  'wegwerfemail.de', 'wegwerfemail.info', 'wegwerfemail.net',
  'wegwerfemail.org', 'wetrainbayarea.com', 'wetrainbayarea.org',
  'whatpaas.com', 'whopy.com', 'whyspam.me', 'willhackforfood.biz',
  'willselfdestruct.com', 'winemaven.info', 'witam.net', 'wnetz.de',
  'wolfsrudel.com', 'worksucks.com', 'worldspace.link', 'wuuvo.com',
  'wwwnew.eu', 'wwwnew.net',
  'x1x.spb.ru', 'xagloo.com', 'xakl.ml', 'xcompress.com',
  'xcoxc.com', 'xemaps.com', 'xemaps.net', 'xents.com',
  'xitroo.de', 'xlq.nl', 'xmail.cc', 'xn--9kq967o.com',
  'xoops.com', 'xost.us', 'xyzmail.tk', 'xyzposte.tk',
  'yaela.com', 'yapped.net', 'yeah.net', 'yep.it',
  'yogamaven.com', 'yopmail.com', 'yopmail.fr', 'yopmail.gq',
  'you-spam.com', 'yourdomain.com', 'yuurok.com',
  'z1p.biz', 'za.com', 'zagate.com', 'zaktouni.fr',
  'zehnminutenmail.de', 'zippymail.info', 'zoaxe.com', 'zoemail.net',
  'zoemail.org', 'zomg.info', 'zooglemail.com',
]);

/**
 * Extracts the domain portion from an email address.
 * Returns null if the email is malformed.
 */
function extractDomain(email) {
  if (!email || typeof email !== 'string') return null;
  const parts = email.toLowerCase().trim().split('@');
  if (parts.length !== 2 || !parts[1]) return null;
  return parts[1];
}

/**
 * Returns true if the email domain is in the static blocklist.
 */
function isDisposableEmail(email) {
  const domain = extractDomain(email);
  return !!domain && DISPOSABLE_DOMAINS.has(domain);
}

/**
 * Checks MX records for the email's domain using Node.js DNS.
 * Returns true if the domain has at least one valid MX record.
 * Resolves to false on timeout or DNS error (fail-open to avoid blocking legit users).
 * @param {string} email
 * @param {number} [timeoutMs=3000]
 */
async function hasMxRecord(email, timeoutMs = 3000) {
  const domain = extractDomain(email);
  if (!domain) return false;

  const dns = require('dns').promises;

  const raceTimeout = new Promise((resolve) =>
    setTimeout(() => resolve(false), timeoutMs)
  );

  const mxLookup = dns.resolveMx(domain)
    .then((records) => Array.isArray(records) && records.length > 0)
    .catch(() => false);

  return Promise.race([mxLookup, raceTimeout]);
}

module.exports = { isDisposableEmail, hasMxRecord, extractDomain };
